# Production retraining configuration for the best GRU trial discovered via HPO
model_type: 'gru'
experiment_name: 'Production_GRU_Retrain'
output_dir: 'training/runs/Production_GRU_Retrain'
use_mlflow: true
use_pregenerated_data: true
pregenerated_data_path: 'data/training_data_v2_final'
num_workers: 8

tags:
  stage: 'PRODUCTION_RETRAIN'
  model_type: 'gru'
  hpo_trial: 'trial_93'

# Pre-generated dataset generated during Phase 3
data_config:
  use_pregenerated: true
  pregenerated_path: 'data/training_data_v2_final'
  lookback_window: 24
  num_workers: 8

model_config:
  type: 'gru'
  gru_hidden_dim: 128
  gru_num_layers: 2
  dropout_rate: 0.3
  attention_dim: 64
  asset_embedding_dim: 16
  use_layer_norm: true
  bidirectional: false

training_config:
  epochs: 100
  min_epochs: 15
  batch_size: 128
  learning_rate: 0.0005
  min_learning_rate: 0.0004
  optimizer: 'adamw'
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  use_amp: true
  use_weighted_sampling: false

  loss_function:
    type: 'focal'
    alpha: 0.25
    gamma: 2.0

  scheduler: 'reduce_on_plateau'
  scheduler_mode: 'max'
  scheduler_factor: 0.5
  scheduler_patience: 10

  early_stopping_patience: 20
  monitor_metric: 'f1'

experiment:
  name: 'Production_GRU_Retrain'
  stage: 'PRODUCTION_RETRAIN'
  purpose: 'production_hpo_retrain'
  tags:
    model_type: 'gru'
    hpo_trial: 'trial_93'
